window.addEventListener('load',()=>document.querySelector('.loader').classList.add('done'));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('visible')}),{threshold:.14});
document.querySelectorAll('.section,.hero-content,.service-card,.stat-row div,.territory-tags span').forEach((el,index)=>{el.classList.add('reveal');el.style.transitionDelay=`${Math.min(index%5,4)*90}ms`;revealObserver.observe(el)});
const hero=document.querySelector('.hero'),heroImage=document.querySelector('.hero-image'),heroLight=document.querySelector('.hero-light'),heroContent=document.querySelector('.hero-content'),heroGrid=document.querySelector('.hero-grid'),canvas=document.querySelector('.terrain-canvas'),ctx=canvas&&canvas.getContext('2d');let progress=0,scrollTick=false;
function resizeCanvas(){if(!canvas)return;canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}
function drawScene(t=0){if(!ctx)return;const w=innerWidth,h=innerHeight;ctx.clearRect(0,0,w,h);const p=progress;
  ctx.save();ctx.globalAlpha=.3+.7*p;ctx.beginPath();ctx.moveTo(w*.42,h*.72);ctx.lineTo(w*.58,h*(.39-p*.04));ctx.lineTo(w*.7,h*.72);ctx.closePath();ctx.fillStyle='#202923';ctx.fill();ctx.beginPath();ctx.moveTo(w*.18,h*.72);ctx.lineTo(w*.38,h*(.5-p*.06));ctx.lineTo(w*.51,h*.72);ctx.closePath();ctx.fillStyle='#151c18';ctx.fill();ctx.restore();
  ctx.save();ctx.translate(w*.74,h*.66);ctx.scale(.7+p*.35,.7+p*.35);ctx.rotate((p-.5)*.05);ctx.strokeStyle='rgba(201,130,82,.86)';ctx.fillStyle='rgba(17,19,17,.92)';ctx.lineWidth=3;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-80,70);ctx.lineTo(68,70);ctx.moveTo(-54,70);ctx.lineTo(-10,-62);ctx.lineTo(32,70);ctx.moveTo(-35,15);ctx.lineTo(16,15);ctx.moveTo(-26,-23);ctx.lineTo(28,-23);ctx.moveTo(-10,-62);ctx.lineTo(45,-12);ctx.stroke();ctx.fillRect(-72,62,140,12);ctx.beginPath();ctx.moveTo(-5,-20);ctx.lineTo(75,25);ctx.lineTo(65,34);ctx.lineTo(-12,-10);ctx.closePath();ctx.fillStyle='#c98252';ctx.fill();const pump=Math.sin(t*.002)*16*p;ctx.beginPath();ctx.moveTo(65,29);ctx.lineTo(96,55+pump);ctx.lineTo(91,59+pump);ctx.lineTo(60,35);ctx.stroke();ctx.restore();
  for(let j=0;j<18;j++){ctx.beginPath();for(let x=-40;x<w+40;x+=18){const y=h*(.55+j*.035)+Math.sin(x*.009+j*.7+p*5+t*.0003)*28+Math.sin(x*.021-p*3)*14-p*j*2;x===-40?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.strokeStyle=`rgba(201,130,82,${.14+(j/18)*.24})`;ctx.lineWidth=1;ctx.stroke()}requestAnimationFrame(drawScene)}
resizeCanvas();drawScene();addEventListener('resize',resizeCanvas);
addEventListener('scroll',()=>{if(scrollTick)return;scrollTick=true;requestAnimationFrame(()=>{const y=scrollY,total=hero.offsetHeight-innerHeight;progress=Math.max(0,Math.min(1,y/total));heroImage.style.transform=`scale(${1.04+progress*.22}) translate3d(${progress*-3}%,${progress*-7}%,0)`;heroImage.style.filter=`saturate(${.72+progress*.28}) contrast(${1.1+progress*.12}) brightness(${.85+progress*.18})`;heroLight.style.transform=`translate3d(${progress*18}px,${progress*24}px,0) scale(${1+progress*.5})`;heroContent.style.transform=`translate3d(0,${progress*-45}px,0) scale(${1-progress*.08})`;heroContent.style.opacity=String(1-progress*.78);heroGrid.style.transform=`translate3d(${progress*-24}px,${progress*-18}px,0) scale(${1+progress*.08})`;scrollTick=false})},{passive:true});
addEventListener('pointermove',e=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const x=(e.clientX/innerWidth-.5)*2,y=(e.clientY/innerHeight-.5)*2;heroImage.style.marginLeft=`${x*-7}px`;heroLight.style.marginLeft=`${x*18}px`;heroGrid.style.transform=`translate3d(${x*7}px,${y*5}px,0)`},{passive:true});
